
nivel_servicio={
  'Atencion Al Cliente':'N1',
  'Atencion Al Cliente - ACTIVACIONES OPERADORES':'N2',
  'Atencion Al Cliente - ATENCION EMPRESAS':'N1',
  'Atencion Al Cliente - ATENCION OPERADORES':'N1',
  'Atencion Al Cliente - SOPORTE EMPRESAS':'N1',
  'Atencion Al Cliente - SOPORTE OPERADORES':'N1',
  'Atencion Al Cliente - CONFIGURACIÃ“N Y AUTOINSTALABLES':'N1',
  'Atencion Al Cliente - MANTENIMIENTO EMPRESAS':'N2',
  'Atencion Al Cliente - MANTENIMIENTO NEUTRA':'N2',
  'Atencion Al Cliente - MANTENIMIENTO OPERADORES':'N2',
  'Atencion Al Cliente - MANTENIMIENTO RESELLER':'N2',
  'Departamento Financiero':'N3-FIN',
  'Departamento Financiero - FINANCIERO':'N3-FIN',
  'Departamento Red':'N2',
  'Departamento Red - ING.DATOS':'N2',
  'Departamento Red - ING.VOZ':'N2',
  'Departamento Red - O&M':'N2',
  'Departamento Red - PLATAFORMAS':'N2',
  'Departamento Red - INFRAESTRUCTURAS':'N2',
  'Departamento Sistemas':'N2',
  'Departamento Sistemas - MVNO':'N1',
  'Departamento Sistemas - SISTEMAS':'N1',
  'Implantacion - IMPLANTACION-INCIDENCIAS':'SD',
  'Portabilidad':'SD',
  'Provision':'SD',
  'Provision - PROVISION':'SD',
  'Provision - PROVISION-BAJAS':'SD',
  '':'N1'
}
